name: CI/CD

on: [push,pull_request]

env:
  NODE_VERSION: '20'

jobs:
  build-and-lint:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: ./.github/workflows/setup-node-yarn-cache.yml
        with:
          os: ${{ matrix.os }}
          node-version: ${{ env.NODE_VERSION }}
      - name: Run Tests and Lint
        run: yarn test && yarn lint

  snyk-security:
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/workflows/setup-node-yarn-cache.yml
        with:
          os: ubuntu-latest
          node-version: ${{ env.NODE_VERSION }}
      - name: Run Snyk to check for vulnerabilities
        run: npx snyk test --all-projects

  # run from github ui
  #analyze:
  #  name: Analyze
  #  runs-on: ubuntu-latest
  #  steps:
  #  - name: Checkout repository
  #    uses: actions/checkout@v2
  #  - name: Initialize CodeQL
  #    uses: github/codeql-action/init@v1
  #    with:
  #      languages: "javascript,typescript"
  #  - name: Autobuild
  #    uses: github/codeql-action/autobuild@v1
  #  - name: Perform CodeQL Analysis
  #    uses: github/codeql-action/analyze@v1


  #release:
  #  runs-on: ubuntu-latest
  #  if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/')
  #  steps:
  #    - name: Checkout
  #      uses: actions/checkout@v2
  #    - name: Install dependencies
  #      run: npm install
  #    - name: Package Extension
  #      run: vsce package
  #    - name: Publish to Marketplace
  #      uses: HaaLeo/publish-vscode-extension@v0
  #      with:
  #        pat: ${{ secrets.VSCE_TOKEN }}
  #        vsix: *.vsix
