name: Setup Node, Yarn, and Cache

on:
  workflow_call:
    inputs:
      node-version:
        required: true
        type: string

jobs:
  setup:
    name: Setup Node
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          node-version: ${{ inputs.node-version }}
          cache: 'yarn'
      - name: Install Yarn
        run: yarn install --frozen-lockfile
